- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
    
    - name: install nginx server
      ansible.builtin.packages:
        name: nginx
        state: present
    
    - name: start nginx server
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
      
    - name: remove html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: create html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    
